drop table if exists bookmarks_table;

-- Create table
create table if not exists bookmarks_table
(
    id integer primary key generated by default as identity,
    title text not null,
    url text not null unique,
    description text default '',
    rating numeric not null constraint rating_limit check (rating >= 0 and rating <= 5)
);

insert into bookmarks_table
(title, url, description, rating)
values
('Google', 'https://www.google.com', 'Find anything and everything', 4.5),
('Thinkful', 'https://www.thinkful.com', 'Learn career changing skills', 5),
('Gamebattles', 'https://www.gamebattles.com', 'Prove your gaming skills', 3),
('Github', 'https://www.github.com', 'Share your code with the world', 2.5),
('Youtube', 'https://www.youtube.com', 'Find videos', 3.5),
('Twitter', 'https://www.twitter.com', 'stay connected with the world', 5);

select * from bookmarks_table;